
import { GlobalProvider } from '@/redux/GlobalProvider.tsx'
import './globals.css'
import Navbar from '@/components/layouts/Navbar'
export const metadata = {
  title: 'Blitz',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='min-h-screen'>
				<GlobalProvider>
					<Navbar/>
					{children}
				</GlobalProvider>
			</body>
    </html>
  )
}
